create table if not exists users
(
    id          bigint generated by default as identity primary key,
    telegram_id bigint unique not null,
    username    varchar(255)  null,
    created_at  timestamp default now()
);

create table if not exists currencies
(
    id    bigint generated by default as identity primary key,
    code  varchar(5) unique not null,
    name  VARCHAR(50)       NOT NULL,
    value NUMERIC(10, 2)    NOT NULL
);


create table if not exists exchange_rates
(
    id          bigint generated by default as identity primary key,
    value        NUMERIC(10, 2) NOT NULL,
    rate_date   TIMESTAMP      NOT NULL,
    currency_id BIGINT         REFERENCES currencies (id) ON DELETE SET NULL
);

create table if not exists subscriptions
(
    id               bigint generated by default as identity primary key,
    is_active        BOOLEAN   NOT NULL default false,
    last_notified_at TIMESTAMP NOT NULL,
    user_id          BIGINT    REFERENCES users (id) ON DELETE SET NULL,
    currency_id      BIGINT    REFERENCES currencies (id) ON DELETE SET NULL,
    CONSTRAINT unique_user_currency UNIQUE (user_id, currency_id)
);