telegram.bot.token=
telegram.bot.username=

cbr.api.url=https://www.cbr-xml-daily.ru/daily_json.js

db.url=cbr-monitoring
db.username=cbr-monitoring
db.password=cbr-monitoring
db.driver-class-name=org.postgresql.Driver

hibernate.show-sql=true
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update